testing #362: created unit tests for sending answers on the survey
fictadvisor/fictadvisor-api pull request #391
Opened 2023-06-11 17:36 UTC by f-ogoog

- added test for getUniqueQuestions
- added test for checkRequiredQuestions
- added test for checkExcessiveQuestions
- added test for checkIsUnique
- added test for checkIfArrayIsUnique
- added test for checkSendingTime 
closes #362

2023-06-11 20:48 UTC, basarabst commented on src/v2/api/services/DisciplineTeacherService.spec.ts
> +  beforeEach(async () => {
try to use beforeAll to prevent redundant generation of Prisma Client as you import PrismaModule

2023-06-11 20:48 UTC, basarabst commented on src/v2/api/services/DisciplineTeacherService.spec.ts
> +    });
Here you are actually testing the actual mock, so I don't see the point of this test

2023-06-11 20:48 UTC, basarabst commented on src/v2/api/services/DisciplineTeacherService.spec.ts
> +    it('should trow NotEnoughAnswersException if there are not enough answers', async () => {
spelling mistake

2023-06-11 20:48 UTC, basarabst commented on src/v2/api/services/DisciplineTeacherService.spec.ts
> +      }
2 spaces after await; since the call is asynchronous it is better to use `.catch((err) => ...)`

2023-06-11 20:48 UTC, basarabst commented on src/v2/api/services/DisciplineTeacherService.spec.ts
> +        expect(err).toBeInstanceOf(ExcessiveAnswerException);
the same problem

2023-06-11 20:48 UTC, basarabst commented on src/v2/api/services/DisciplineTeacherService.spec.ts
> +      }
the same problem

2023-06-11 20:48 UTC, basarabst commented on src/v2/api/services/DisciplineTeacherService.spec.ts
> +        }
the same problem

2023-06-11 20:55 UTC, basarabst commented
Also, methods that are not used outside the tested service should be made private and not tested

2023-06-11 21:41 UTC, just-hoshinon requested changes

2023-06-11 21:41 UTC, just-hoshinon commented on src/v2/api/services/DisciplineTeacherService.spec.ts
> +    const testingModule = await Test.createTestingModule({
There are so many modules, which are not used during the tests. You should use .useMocker() method to avoid so many dependencies in module.

2023-06-12 11:49 UTC, just-hoshinon approved these changes

2023-06-12 11:50 UTC, merged