feature #427: created attach selective discipline endpoint
fictadvisor/fictadvisor-api pull request #453
Opened 2023-06-18 14:42 UTC by f-ogoog

- created endpoint which attach selective discipline to User
- added AlreadySelectedException, ExcessiveSelectiveDisciplinesException, NotApprovedException, NotBelongToGroupException exceptions
- added AttachSelectiveDisciplinesDTO
- added SelectiveDisciplinesPipe StudentByApprovedPipe
- added swagger documentation to this endpoint

closes #427

2023-06-22 17:23 UTC, basarabst requested changes

2023-06-22 17:23 UTC, basarabst commented on src/v2/api/pipes/StudentByApprovedPipe.ts
> +export class StudentByApprovedPipe implements PipeTransform {
change naming

2023-06-22 18:14 UTC, just-hoshinon requested changes

2023-06-22 18:14 UTC, just-hoshinon commented on src/v2/api/services/DisciplineService.ts
> +  private async checkExcessiveSelectiveDisciplines (sortedDisciplines, sortedSelectedDisciplines, groupId) {
types:
```ts
type SortedDisciplines = {
  year: number;
  semester: number;
  disciplines: string[];
}
```

2023-06-22 18:14 UTC, just-hoshinon commented on src/v2/api/services/DisciplineService.ts
> +    for (const period of sortedDisciplines) {
can be simplified to: 
```ts
for (const { year, semester, disciplines } of pendingDisciplines) {
    const pendingAmount = disciplines.length;
    const selectedAmount = selectedDisciplines
    .find((p) => p.year === year && p.semester === semester)
    ?.disciplines.length ?? 0;
  ```

2023-06-22 18:14 UTC, just-hoshinon commented on src/v2/api/services/DisciplineService.ts
> +  private getSortedDisciplinesByPeriod (disciplines) {
type

2023-06-22 18:14 UTC, just-hoshinon commented on src/v2/api/services/DisciplineService.ts
> +  private async attachSelectiveDisciplines (userId, disciplines) {
types

2023-06-22 18:14 UTC, just-hoshinon commented on src/v2/api/services/DisciplineService.ts
> +  async selectDisciplines (userId, body) {
types

2023-06-22 22:22 UTC, just-hoshinon approved these changes

2023-06-22 22:34 UTC, just-hoshinon approved these changes

2023-06-22 22:36 UTC, just-hoshinon approved these changes

2023-06-23 07:20 UTC, basarabst approved these changes

2023-06-23 11:04 UTC, merged