Enhancement/add pagination of teacher comments
fictadvisor/fictadvisor-api pull request #496
Opened 2023-06-25 11:50 UTC by SharpDevOps10

2023-06-26 16:42 UTC, basarabst requested changes
Because of your changes, the function returns a completely empty array with no information about the question, this will need fixing

2023-06-26 16:42 UTC, basarabst commented on src/v2/api/services/PollService.ts
> +          orderBy: query.sortBy ? CommentsSortMapper[query.sortBy] : undefined,
previous version is more readable

2023-06-26 17:57 UTC, basarabst approved these changes

2023-06-27 08:42 UTC, Hahhhayam submitted a review, later dismissed
![image](https://github.com/fictadvisor/fictadvisor-api/assets/104493134/4e950a16-1dca-40e9-b449-2fb6d838e2a6)
don`t throw an exeption when user set unexisting subjectId

2023-06-27 09:38 UTC, Hahhhayam approved these changes

2023-06-27 16:47 UTC, just-hoshinon approved these changes

2023-06-27 16:47 UTC, just-hoshinon commented on src/v2/api/dtos/CommentsQueryDTO.ts
> +  @IsOptional()
Should be shown in the swagger

2023-06-27 16:47 UTC, just-hoshinon commented on src/v2/api/services/PollService.ts
> +    return await this.questionRepository.findMany(questionFindManyArgs) as DbQuestionWithDiscipline[];
excessive await

2023-06-27 20:19 UTC, merged