bugfix #470: fix bug in pagination
fictadvisor/fictadvisor-api pull request #513
Opened 2023-06-28 12:08 UTC by ArtemiiLiakh

- added a feature to DatabaseUtils which gets objects from repository and uses pagination
- changed services where the feature must be used
- added paginated responses with pagination data for swagger
- changed tests

closes #470

2023-06-28 19:13 UTC, f-ogoog approved these changes

2023-06-29 13:14 UTC, basarabst requested changes
Are you sure that information about the number of elements of the previous page will be useful?

2023-06-29 14:33 UTC, basarabst approved these changes

2023-06-29 19:01 UTC, just-hoshinon approved these changes

2023-06-29 19:01 UTC, merged