bugfix #509: fixed rating pagination
fictadvisor/fictadvisor-api pull request #514
Opened 2023-06-29 12:35 UTC by f-ogoog

- now one large request is sent to the database instead of many small ones

closes #509

2023-07-01 08:09 UTC, basarabst requested changes

2023-07-01 08:09 UTC, basarabst commented on src/v2/api/services/SubjectService.ts
> +      }));
move it to mapper

2023-07-01 08:09 UTC, basarabst commented on src/v2/api/services/TeacherService.ts
> +      }));
move it to mapper to avoid duplication

2023-07-01 14:26 UTC, Hahhhayam approved these changes

2023-07-02 14:29 UTC, basarabst approved these changes

2023-07-02 15:31 UTC, just-hoshinon requested changes

2023-07-02 15:31 UTC, just-hoshinon commented on src/v2/api/services/SubjectService.ts
> +      include: {
Where is the new type of this sctructure?

2023-07-02 15:31 UTC, just-hoshinon commented on src/v2/mappers/QuestionMapper.ts
> +  getSortedQuestionsWithAnswers (disciplineTeachers) {
where is the type

2023-07-02 15:31 UTC, just-hoshinon commented on src/v2/mappers/QuestionMapper.ts
> +        if (question.type === QuestionType.TEXT) continue;
you can do filtration in the database request

2023-07-02 15:31 UTC, just-hoshinon commented on src/v2/mappers/QuestionMapper.ts
> +  getRightMarkFormat ({ display, type, questionAnswers: answers }) {
where is the type

2023-07-02 15:31 UTC, just-hoshinon commented on src/v2/api/services/TeacherService.ts
>      };
Where is the type

2023-07-02 15:31 UTC, just-hoshinon commented on src/v2/mappers/QuestionMapper.ts
> +  getMarks (questionWithAnswers) {
Where is the type

2023-07-05 21:12 UTC, just-hoshinon approved these changes

2023-07-05 21:18 UTC, merged