bugfix #460: added correct sorting of teachers
fictadvisor/fictadvisor-api pull request #519
Opened 2023-06-30 17:57 UTC by SharpDevOps10

- added several sorting fields
- added array to which sort objects are attached for each field
- sorted all fields

closes #408

2023-07-01 12:10 UTC, Hahhhayam requested changes
remove unnessary varaibles, like: 
![image](https://github.com/fictadvisor/fictadvisor-api/assets/104493134/cd3c0f58-7dac-4a29-ae8f-f0eec4b148e1)
if you think, that your version more readable, close this request

2023-07-01 12:47 UTC, Hahhhayam approved these changes

2023-07-03 19:04 UTC, f-ogoog approved these changes

2023-07-03 21:50 UTC, just-hoshinon requested changes

2023-07-03 21:50 UTC, just-hoshinon commented on src/v2/mappers/TeacherMapper.ts
> +  getSortedTeacher ({ sort, order = OrderQAParam.ASC }: SortDTO): Sort | object {
you can do sort as you do orded:
```ts
{ sort = SortQATParam.LAST_NAME, order = OrderQAParam.ASC }
```

2023-07-03 21:50 UTC, just-hoshinon commented on src/v2/mappers/TeacherMapper.ts
> +    if (!sort) sort = SortQATParam.LAST_NAME;
this field will be redundant

2023-07-03 21:50 UTC, just-hoshinon commented on src/v2/mappers/TeacherMapper.ts
> +    const orderBy = sort.split(',').map((field) => ({
front-end will never send more than one value from enum, so splitting and mapping is reduntant, as well as trimming

2023-07-04 17:55 UTC, just-hoshinon approved these changes

2023-07-04 17:55 UTC, merged