refactoring #414: refactored events creating
fictadvisor/fictadvisor-api pull request #548
Opened 2023-07-11 23:45 UTC by f-ogoog

- rewrote event creating in ScheduleParser
- reduced the number of requests to database

closes #414

2023-07-14 12:54 UTC, basarabst requested changes

2023-07-14 12:54 UTC, basarabst commented on src/v2/utils/parser/ScheduleParser.ts
>      }
are you sure that the second check will ever be done?

2023-07-14 20:16 UTC, kropli approved these changes

2023-07-14 20:26 UTC, kropli requested changes

2023-07-14 20:26 UTC, kropli commented on src/v2/utils/date/DateService.ts
> +  getSemester (period) {
Untyped parameter

2023-07-15 16:30 UTC, kropli approved these changes

2023-07-15 21:50 UTC, just-hoshinon requested changes

2023-07-15 21:50 UTC, just-hoshinon commented on src/v2/utils/parser/ScheduleParser.ts
> +    const eventInfo = [];
```ts
return Array.from({
      length: endIndex - startIndex + 1,
    }, (_, i) => ({
      number: i + startIndex,
    }));
```

2023-07-16 21:13 UTC, just-hoshinon approved these changes

2023-07-16 21:14 UTC, merged