enhancement #528: added total pages field for meta
fictadvisor/fictadvisor-api pull request #557
Opened 2023-07-16 21:21 UTC by ArtemLyah

- renamed meta to pagination field
- added totalPages field to pagination
- added method count to repositories which are used in pagination

closes #528

2023-07-19 15:01 UTC, kropli approved these changes

2023-07-19 18:06 UTC, SharpDevOps10 requested changes

2023-07-19 18:09 UTC, ArtemLyah commented on src/v2/api/controllers/ResourceController.ts
> +    return {
It isn't my task

2023-07-20 19:16 UTC, SharpDevOps10 approved these changes

2023-07-20 22:12 UTC, just-hoshinon requested changes

2023-07-20 22:12 UTC, just-hoshinon commented on src/v2/api/dtos/CreateResourceDTO.ts
> +  @ApiProperty()
can be optional

2023-07-22 19:18 UTC, just-hoshinon approved these changes

2023-07-22 19:18 UTC, merged