feature #532: Add endpoint for group member on schedule
fictadvisor/fictadvisor-api pull request #564
Opened 2023-07-19 20:40 UTC by kropli

- implemented getGroupEvents method
- added getAllGroupEvents methods in ScheduleService
- added GroupEventResponse
- added integration tests for getGroupEvents
- described swagger documentation

closes #532

2023-07-19 21:13 UTC, just-hoshinon requested changes

2023-07-19 21:13 UTC, just-hoshinon commented on src/v2/api/services/UserService.ts
> +    if (isOwnSelected) {
if it's not user's group, you don't need to filter selective disciplines

2023-07-19 21:13 UTC, just-hoshinon commented on src/v2/api/services/UserService.ts
> +        event.lessons = event.lessons
no filtration of events

2023-07-28 11:14 UTC, just-hoshinon requested changes

2023-07-28 11:14 UTC, just-hoshinon commented on src/v2/api/services/ScheduleService.ts
> +            selectiveDiscipline.id === lesson.disciplineType.disciplineId);
you can use ArrayUtils method:
```ts
some(userSelective, 'id', lesson.disciplineType.disciplineId);
```

2023-07-28 11:14 UTC, just-hoshinon commented on src/v2/api/services/ScheduleService.ts
> +    }) as unknown as DbEvent[];
It's better to declare type in EventRepository:
```ts
async findMany(...): Promise<DbEvent[]> {

}
```

2023-07-28 11:14 UTC, just-hoshinon commented on src/v2/api/services/ScheduleService.ts
> +  async getAllGroupEvents (id, week) {
you can rename id to groupId

2023-07-28 11:14 UTC, just-hoshinon commented on src/v2/api/services/ScheduleService.ts
> +        groupId: id,
after changing id to groupId you can write just `groupId,`

2023-07-28 11:14 UTC, just-hoshinon commented on src/v2/api/services/ScheduleService.ts
> +          return true;
making else in a such way is a bad practice. you can revert your if-statement, making it more readable:
```ts
const discipline = ...;
if (!discipline.isSelective) return true;

return some(...);
```

2023-07-28 11:14 UTC, just-hoshinon commented on src/v2/api/responses/AllEventResponse.ts
> +  @ApiPropertyOptional({
It's not optional. Optional means undefined. This field can be type or null, not undefined

2023-07-28 11:14 UTC, just-hoshinon commented on src/v2/api/controllers/ScheduleController.ts
> +    return this.scheduleMapper.getGeneralEvents(events);
it will be better to rename this method to getEvents

2023-07-30 18:06 UTC, just-hoshinon requested changes
Make endpoint return week and events in object

2023-08-01 15:28 UTC, JessFreak commented on src/v2/mappers/ScheduleMapper.ts
> +  getEvents (events: DbEvent[])  {
extra space

2023-08-01 15:29 UTC, JessFreak approved these changes

2023-08-02 17:47 UTC, PavloVlasiuk commented on src/v2/api/controllers/ScheduleController.ts
> +  @Access('groups.$groupId.events.get')
add authorization to swagger documentation

2023-08-02 17:47 UTC, PavloVlasiuk commented on src/v2/api/controllers/ScheduleController.ts
> +      events: this.scheduleMapper.getEvents(result.events),
describe returned value disciplineType correctly. Follow this example 
![image](https://github.com/fictadvisor/fictadvisor-api/assets/113940774/3c586c96-7fd5-442c-a170-de011e3d9cb2)

2023-08-02 17:47 UTC, PavloVlasiuk commented on src/v2/api/controllers/ScheduleController.ts
> +    InvalidEntityIdException:
this exception must be InvalidGroupIdException

2023-08-08 08:52 UTC, JessFreak approved these changes

2023-08-08 08:52 UTC, JessFreak commented on src/v2/api/services/ScheduleService.ts
> +      console.log('res1: ', res1, ' res2: ', res2, ' res3: ', res3, ' res4: ', res4);
did not clean colnsole.log

2023-08-12 10:15 UTC, f-ogoog commented on src/v2/api/services/ScheduleService.ts
> +        await this.setWeekTime(event, week);
period in this case can not be NO_PERIOD

2023-08-12 14:39 UTC, merged