feature #543: created endpoint to update event
fictadvisor/fictadvisor-api pull request #570
Opened 2023-07-25 20:18 UTC by f-ogoog

- created new endpoint to update event
- added UpdateEventDTO, EventPipe

closes #543

2023-07-25 21:11 UTC, just-hoshinon requested changes

2023-07-25 21:11 UTC, just-hoshinon commented on src/v2/api/dtos/UpdateEventDTO.ts
> +    disciplineDescription?: string;
disciplineInfo

2023-07-25 21:11 UTC, just-hoshinon commented on src/v2/api/dtos/UpdateEventDTO.ts
> +    pairDescription?: string;
eventInfo

2023-07-25 21:11 UTC, just-hoshinon commented on src/v2/api/dtos/UpdateEventDTO.ts
> +  @ApiPropertyOptional()
add enum recognition

2023-07-25 21:11 UTC, just-hoshinon commented on src/v2/api/services/ScheduleService.ts
> +      update.disciplineTypes = {
It's not correct. Changing the type doesn't change the discipline type entity. It disconnects and connects another discipline type

2023-07-25 21:11 UTC, just-hoshinon commented on src/v2/api/services/ScheduleService.ts
> +        if (!teachers.some((t) => disciplineTeacher.teacherId === t)) {
We have util method for such purposes

2023-07-30 11:11 UTC, kropli requested changes

2023-07-30 19:45 UTC, kropli approved these changes

2023-08-07 13:03 UTC, Hahhhayam requested changes

2023-08-07 13:03 UTC, Hahhhayam commented on src/v2/api/services/ScheduleService.ts
> +    update.description = disciplineInfo ? disciplineInfo : undefined;
use null-union ??

2023-08-12 19:14 UTC, basarabst requested changes

2023-08-12 19:14 UTC, basarabst commented on src/v2/api/services/ScheduleService.ts
> +      const countOfPair = period === Period.EVERY_FORTNIGHT ? Math.floor(countOfWeek/2) : countOfWeek;
spaces " /  "

2023-08-12 19:14 UTC, basarabst commented on src/v2/api/services/ScheduleService.ts
> +          data: this.scheduleParser.getIndexesForEventInfo(event.eventInfo.length, event.eventInfo.length+pairDifference-1),
spaces

2023-08-12 19:14 UTC, basarabst commented on src/v2/api/services/ScheduleService.ts
> +            gte: countOfPair-1,
spaces

2023-08-12 19:14 UTC, basarabst commented on src/v2/api/services/ScheduleService.ts
> +      if (!type || !teachers) throw new ObjectIsRequiredException('disciplineType and teachers');
split exception into 2 for readability

2023-08-12 19:57 UTC, basarabst approved these changes

2023-08-12 21:00 UTC, SharpDevOps10 approved these changes

2023-08-19 16:21 UTC, just-hoshinon approved these changes

2023-08-19 16:30 UTC, merged