refactoring #482: Changed filtering of primitive arrays with Set object
fictadvisor/fictadvisor-api pull request #576
Opened 2023-07-26 19:19 UTC by JessFreak

- refactored DisciplineTeacherMapper.getRoles
- refactored DisciplineTeacherService.getUniqueQuestions
- refactored TeacherMapper.getUniqueQuestions
- improved the style of some code

closes #482

2023-07-29 18:57 UTC, Hahhhayam requested changes

2023-07-29 18:57 UTC, Hahhhayam commented on src/v2/api/services/DisciplineTeacherService.ts
>      const disciplineRoles = [];
I think it`s better to change disciplineRoles type to Set, because, if you want put some logic after for cycle, you will work with "dirty" array.

2023-07-29 18:57 UTC, Hahhhayam commented on src/v2/mappers/DisciplineTeacherMapper.ts
>      const roles = [];
Same case. Also, you should return an array

2023-07-29 18:57 UTC, Hahhhayam commented on src/v2/mappers/TeacherMapper.ts
> +      roles.push(...dt.roles.map((r) => r.role));
Same case

2023-07-31 12:40 UTC, Hahhhayam approved these changes

2023-08-01 17:12 UTC, ArtemLyah commented on src/v2/api/services/TeacherService.ts
> +  async getContact (teacherId: string,
arguments must be in a single line

2023-08-01 17:13 UTC, ArtemLyah commented on src/v2/api/services/TeacherService.ts
> +    name: string) {
arguments must be in a single line

2023-08-01 18:14 UTC, ArtemLyah approved these changes

2023-08-01 18:51 UTC, merged