feature #575: created endpoint to get fortnight events
fictadvisor/fictadvisor-api pull request #632
Opened 2023-08-24 11:45 UTC by f-ogoog

- created endpoint to get fortnight events
- added documentation

closes #575

2023-08-24 13:34 UTC, SharpDevOps10 requested changes

2023-08-24 13:34 UTC, SharpDevOps10 commented on src/v2/api/controllers/ScheduleController.ts
> +      eventsOfSecondWeek: this.scheduleMapper.getEvents(result.eventsOfSecondWeek),
In this case I`d rather shorten: 
* `eventsOfFirstWeek` to `firstWeekEvents`;
* `eventsOfSecondWeek` to `secondWeekEvents`.

2023-08-24 13:34 UTC, SharpDevOps10 commented on src/v2/api/responses/EventsResponse.ts
> +    eventsOfSecondWeek: GeneralEventInfoResponse[];
In this case I`d rather shorten: 
* `eventsOfFirstWeek` to `firstWeekEvents`;
* `eventsOfSecondWeek` to `secondWeekEvents`.

2023-08-24 16:44 UTC, SharpDevOps10 approved these changes

2023-08-25 15:02 UTC, ArtemLyah commented on src/v2/api/services/ScheduleService.ts
> +    return { firstWeekEvents, secondWeekEvents };
Use DataNotFoundException when firstWeekEvents and secondWeekEvents are empty

2023-08-25 15:04 UTC, kropli approved these changes

2023-08-25 15:31 UTC, merged