documentation #631: added swagger documentation for 7 roles endpoints
fictadvisor/fictadvisor-api pull request #633
Opened 2023-08-25 12:46 UTC by illiakroshka

Get:
- /roles
- /roles/{roleId}
- /roles/{roleId}/grants

Post:
- /roles
- /roles/{roleId}/grants

Patch:
- /roles/{roleId}

closes #631

2023-08-25 18:56 UTC, basarabst requested changes

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +                  Your parent role weight is bigger than role weight`,
doesn't exist

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +                  You do not have permission to perform this action
too mauch spaces
pattern: https://gist.github.com/Hahhhayam/43197ad702006f475eb8d97fb8c08814

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
>    @Access('roles.create')
add 
![image](https://github.com/fictadvisor/fictadvisor-api/assets/114052215/a13e1ed9-9a58-4bb6-8e6b-db0a7a679883)

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +                  role with such id is not found`,
doesn't exist

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +                  You do not have permission to perform this action`,
remove spaces

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +                  role with such id is not found`,
doesn't exist

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +                  role with such id is not found`,
doesn't exist

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
>    @Access('roles.$roleId.delete')
add UnauthorizedException

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +                  You do not have permission to perform this action`,
spaces

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +                  role with such id is not found`,
doesn't exist

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +  })
remove spaces

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/responses/GrantResponse.ts
> +  permission: string;
linter

2023-08-25 18:56 UTC, basarabst commented on src/v2/api/responses/GrantResponse.ts
> +  grants: Grant[];
linter

2023-08-27 07:28 UTC, basarabst requested changes

2023-08-27 07:28 UTC, basarabst commented on src/v2/api/dtos/CreateRoleWithGrantsDTO.ts
> +  @ApiPropertyOptional()
```
@ApiPropertyOptional({
    type: [CreateGrantDTO],
  })
  ```

2023-08-27 07:28 UTC, basarabst commented on src/v2/api/dtos/CreateRoleDTO.ts
> +  @ApiProperty()
add
```
{ enum: RoleName }
```

2023-08-27 07:28 UTC, basarabst commented on src/v2/api/responses/GrantResponse.ts
> +  @ApiProperty()
``` type: Role ```

2023-08-27 07:28 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
> +  })
wrong response, see it in Postman

2023-08-27 07:28 UTC, basarabst commented on src/v2/api/controllers/RoleController.ts
>    @Access('roles.$roleId.delete')
where is response?

2023-08-27 07:28 UTC, basarabst commented on src/v2/api/responses/RoleResponse.ts
> +  @ApiProperty()
add
```
{ type: RoleName }
```

2023-08-27 07:31 UTC, basarabst requested changes
Commit message is wrong, see example:
![image](https://github.com/fictadvisor/fictadvisor-api/assets/114052215/ac4a4cf2-ab17-4f98-acf3-e828e74d6c8c)

2023-08-27 07:32 UTC, basarabst requested changes
you have to squash all the commits to one, after that do a force push

2023-08-27 14:03 UTC, basarabst requested changes

2023-08-27 14:03 UTC, basarabst commented on src/v2/api/dtos/UpdateRoleDTO.ts
> +
redundant indentation

2023-08-27 15:30 UTC, basarabst approved these changes

2023-08-28 18:19 UTC, ArtemLyah commented on src/v2/api/dtos/CreateGrantsDTO.ts
> +  @ApiPropertyOptional()
Add default true like there
![image](https://github.com/fictadvisor/fictadvisor-api/assets/63953579/4366528b-da42-4584-9a44-8515c188caf2)

2023-08-28 18:28 UTC, ArtemLyah commented on src/v2/api/controllers/RoleController.ts
> +  @ApiBadRequestResponse({
the CreateRoleWithGrantsDTO uses CreateRoleDTO and CreateGrantDTO so add the following fields
![image](https://github.com/fictadvisor/fictadvisor-api/assets/63953579/0056bbdc-1e9d-45b7-9c6d-5f72d7b338ec)
![image](https://github.com/fictadvisor/fictadvisor-api/assets/63953579/fcf8bc2f-cd8b-40a6-a86e-c29961d0bae1)
like this
![image](https://github.com/fictadvisor/fictadvisor-api/assets/63953579/f780621a-e035-4cd0-8af1-f62347dc5d9d)

2023-08-28 18:43 UTC, ArtemLyah commented on src/v2/api/controllers/RoleController.ts
> +  @Access('roles.$roleId.delete')
delete the Access

2023-08-28 19:08 UTC, ArtemLyah commented on src/v2/api/dtos/UpdateRoleDTO.ts
> +  @ApiPropertyOptional()
Add IsNumber decorator and a validation option message
don't forget to add validation message to "update" endpoint to InvalidBodyException

2023-08-29 10:54 UTC, merged