Documentation/add swagger documentation for groups endpoints
fictadvisor/fictadvisor-api pull request #638
Opened 2023-08-27 13:09 UTC by Ksrebniukk

2023-08-27 15:03 UTC, basarabst requested changes

2023-08-27 15:03 UTC, basarabst commented on src/v2/api/controllers/GroupController.ts
> +    type: StudentsResponse,
this endpoint does not return a group in its response

2023-08-28 16:06 UTC, basarabst approved these changes

2023-08-28 20:14 UTC, f-ogoog commented on src/v2/api/responses/StudentResponse.ts
>    })
you should delete class below and write ApiPropertyOptional

2023-08-29 12:39 UTC, f-ogoog approved these changes

2023-08-29 14:53 UTC, merged