feature #640: Added endpoint to check permissions
fictadvisor/fictadvisor-api pull request #657
Opened 2023-08-30 08:24 UTC by kropli

- created PermissionController
- created PermissionModule
- implemented checkPermissions method
- described documentation

closes #640

2023-09-04 10:42 UTC, fokaaas requested changes

2023-09-04 10:42 UTC, fokaaas commented on src/v2/api/services/PermissionService.ts
> +    }
use pipe instead of this

2023-09-05 06:46 UTC, fokaaas approved these changes

2023-09-06 19:00 UTC, just-hoshinon requested changes

2023-09-06 19:00 UTC, just-hoshinon commented on src/v2/api/dtos/CheckPermissionsDTO.ts
> +    @ApiProperty()
For example: if a permission will be a `admission.create`, there will be no need to use values field. Thus, this field must be optional in these cases.

2023-09-06 19:00 UTC, just-hoshinon commented on src/v2/api/controllers/PermissionController.ts
> +      user with such id is not found
`User`

2023-09-06 19:00 UTC, just-hoshinon commented on src/v2/api/controllers/PermissionController.ts
> +      obj.values: values must be an object
obj.values is optional

2023-09-06 19:00 UTC, just-hoshinon commented on src/v2/api/controllers/PermissionController.ts
> +    return await this.permissionService.checkPermissions(userId, body);
no await

2023-09-06 19:00 UTC, just-hoshinon commented on src/v2/api/services/PermissionService.ts
> +  async checkPermissions (userId: string, { permissions, values }: CheckPermissionsDTO) {
Now values is optional, pay attention

2023-09-07 08:40 UTC, just-hoshinon approved these changes

2023-09-07 11:19 UTC, fokaaas requested changes

2023-09-07 11:19 UTC, fokaaas commented on src/v2/api/services/PermissionService.ts
> +      const valuesForPermission = body.values? body.values : {};
```
const valuesForPermission = body.values ?? {};
```

2023-09-07 11:51 UTC, fokaaas approved these changes

2023-09-07 11:52 UTC, merged