feature #669: implement endpoint for get user by telegramId
fictadvisor/fictadvisor-api pull request #671
Opened 2023-09-01 19:08 UTC by Kulunchick

- implement endpoint for get user by telegramId
- add swagger documentation

2023-09-02 16:04 UTC, basarabst requested changes

2023-09-02 16:04 UTC, basarabst commented on src/v2/api/controllers/UserController.ts
> +  @Get('/:telegramId/telegram-user')
```/telegramUser/:telegramId```

2023-09-02 21:55 UTC, fokaaas requested changes

2023-09-02 21:55 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
> +  @ApiBadRequestResponse({
add description about TelegramUser

2023-09-02 21:55 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
> +  })
This is parameter

2023-09-03 07:08 UTC, fokaaas approved these changes

2023-09-04 11:42 UTC, PavloVlasiuk approved these changes

2023-09-05 08:16 UTC, merged