feature #670: Implemented endpoint for get group by telegramId
fictadvisor/fictadvisor-api pull request #679
Opened 2023-09-03 13:04 UTC by illiakroshka

- implemented endpoint for get group by telegramId
- add swagger documentation

closes #670

2023-09-03 19:54 UTC, f-ogoog commented on src/v2/api/controllers/TelegramGroupController.ts
> +  @ApiParam({ name: 'telegramId', type: 'bigint' })
change type to Number

2023-09-04 17:40 UTC, f-ogoog approved these changes

2023-09-06 15:39 UTC, fokaaas requested changes

2023-09-06 15:39 UTC, fokaaas commented on src/v2/mappers/TelegramGroupMapper.ts
> +  }
move it to a method below

2023-09-07 18:55 UTC, f-ogoog commented on src/v2/mappers/TelegramGroupMapper.ts
> +        group: telegramGroup.group })),
should be enter

2023-09-08 14:50 UTC, fokaaas approved these changes

2023-09-08 14:51 UTC, merged