enhancement #677: improved /v2/users/{userId}/group/{groupId} route:
fictadvisor/fictadvisor-api pull request #700
Opened 2023-09-05 17:08 UTC by JessFreak

- add logic of changing selective disciplines and creating events
- create GroupService.getSelectiveDisciplines
- create ScheduleService.getEventsByDisciplineId

closes #677

2023-09-06 17:50 UTC, fokaaas requested changes

2023-09-06 17:50 UTC, fokaaas commented on src/v2/api/services/UserService.ts
> +    await this.deleteStudentSelective(studentId);
you can get selective disciplines from this method instead of calling ```await this.getSelectiveDisciplines(studentId)```

2023-09-06 17:50 UTC, fokaaas commented on src/v2/api/services/UserService.ts
> +      const exist = newGroupSelective.find((d) => d.subjectId === discipline.subjectId);
In this way you create selective disciplines in new group even if the user did not select them. 
You should create them only under the following condition: **they were chosen by the user, they are not in the new group**

2023-09-06 17:50 UTC, fokaaas commented on src/v2/api/services/UserService.ts
> +    await this.disciplineRepository.create({
How about ```DisciplineTeacherRoles```? 😊

2023-09-07 10:28 UTC, just-hoshinon approved these changes

2023-09-07 10:55 UTC, fokaaas approved these changes

2023-09-07 10:55 UTC, merged