enhancement #672: Changed user contacts endpoints logic
fictadvisor/fictadvisor-api pull request #703
Opened 2023-09-06 18:19 UTC by PavloVlasiuk

- changed /v2/users/{userId}/contacts/{name} patch endpoint to /v2/users/{userId}/contacts/{contactId}
- changed /v2/users/{userId}/contacts/{name} delete endpoint to /v2/users/{userId}/contacts/{contactId}

closes #672

2023-09-07 19:12 UTC, JessFreak requested changes

2023-09-07 19:12 UTC, JessFreak commented on src/v2/api/pipes/ContactByUserIdPipe.ts
> +      throw new InvalidContactIdException();
describe this exception in swagger

2023-09-07 19:12 UTC, JessFreak commented on src/v2/api/controllers/UserController.ts
add swagger documantatin

2023-09-07 19:12 UTC, JessFreak commented on src/v2/api/controllers/UserController.ts
>    @Access(PERMISSION.USERS_$USERID_CONTACTS_DELETE)
add swagger documantatin

2023-09-07 19:13 UTC, JessFreak requested changes

2023-09-07 19:13 UTC, JessFreak commented on src/v2/api/controllers/UserController.ts
> +  @Patch('/:userId/contacts/:contactId')
add swagger documentation

2023-09-07 19:13 UTC, JessFreak commented on src/v2/api/controllers/UserController.ts
> +  @Delete('/:userId/contacts/:contactId')
add swagger documentation

2023-09-07 19:16 UTC, JessFreak reviewed
![image](https://github.com/fictadvisor/fictadvisor-api/assets/119421914/8cef960c-1fa8-47cb-8b7b-74c40d0aed02)
fill this cells

2023-09-08 19:45 UTC, JessFreak approved these changes

2023-09-10 09:04 UTC, Yakorrr commented on src/v2/api/controllers/TelegramGroupController.ts
> -      Data were not found
data WAS not found :)
but it's unnecessary to change

2023-09-10 09:05 UTC, Yakorrr approved these changes

2023-09-10 17:24 UTC, fokaaas approved these changes

2023-09-10 17:25 UTC, merged