bugfix #719: added check for the existence of captain
fictadvisor/fictadvisor-api pull request #721
Opened 2023-09-10 11:03 UTC by ArtemLyah

- added check for existence of captain and captain's telegramId
- added AbsenceOfCaptainTelegramException when captain's telegramId wasn't found

closes #719

2023-09-10 11:58 UTC, f-ogoog commented on src/v2/api/services/AuthService.ts
> +      if (!cap) {
maybe rather write one condition and throw one exception?

2023-09-10 16:19 UTC, f-ogoog approved these changes

2023-09-11 08:58 UTC, illiakroshka requested changes

2023-09-11 08:58 UTC, illiakroshka commented on src/v2/api/controllers/UserController.ts
>      description: `NoPermissionException:\n
Add one more ApiForbiddenResponse exeption to swagger 
![image](https://github.com/fictadvisor/fictadvisor-api/assets/116638814/bbbd813e-a7b9-46bc-9508-45120130d681)
![image](https://github.com/fictadvisor/fictadvisor-api/assets/116638814/c1f77676-854b-49f7-b97b-30089885def4)

2023-09-11 09:42 UTC, illiakroshka approved these changes

2023-09-11 09:56 UTC, fokaaas approved these changes

2023-09-11 09:57 UTC, merged