feature #710:Implemented endpoint for receiving groups with connected…
fictadvisor/fictadvisor-api pull request #722
Opened 2023-09-10 14:07 UTC by illiakroshka

… telegram groups

- implemented for receiving groups with connected telegram groups
- add swagger documentation

closes #710

2023-09-12 16:55 UTC, PavloVlasiuk requested changes

2023-09-12 16:55 UTC, PavloVlasiuk commented on src/v2/api/services/TelegramGroupService.ts
> +
remove one line here

2023-09-12 16:55 UTC, PavloVlasiuk commented on src/v2/api/services/TelegramGroupService.ts
> +  async findGroupsWithTelegramGroups () {
i would name this method getGroupsWithTelegramGroups

2023-09-12 16:55 UTC, PavloVlasiuk commented on src/v2/api/controllers/TelegramGroupController.ts
> +
add ApiBearerAuth here

2023-09-12 16:55 UTC, PavloVlasiuk commented on src/v2/mappers/TelegramGroupMapper.ts
> +      groups: groups.map((telegramGroup) => ({
rename the argument of the first map to group and the the argument of the second map to telegramGroup

2023-09-14 07:25 UTC, PavloVlasiuk approved these changes

2023-09-16 12:04 UTC, Ksrebniukk commented on src/v2/mappers/TelegramGroupMapper.ts
> +          theadId: telegramGroup.threadId,
replace "theadId" with "threadId"

2023-09-16 12:24 UTC, Ksrebniukk approved these changes

2023-09-17 11:01 UTC, fokaaas requested changes

2023-09-17 17:40 UTC, fokaaas approved these changes

2023-09-17 17:40 UTC, merged