enhancement #711:Increase the number of characters in event name
fictadvisor/fictadvisor-api pull request #723
Opened 2023-09-11 11:27 UTC by Ksrebniukk

2023-09-11 14:09 UTC, JessFreak requested changes

2023-09-11 14:09 UTC, JessFreak commented on src/v2/api/dtos/CreateEventDTO.ts
> +  @MaxLength(150, validationOptionsMsg('Name is too long (max: 150)'))
also you should modify the swager documentation that uses this DTO

2023-09-11 14:09 UTC, JessFreak commented on src/v2/api/dtos/UpdateEventDTO.ts
> +  @MaxLength(150, validationOptionsMsg('Name is too long (max: 150)'))
also you should modify the swager documentation that uses this DTO

2023-09-11 14:10 UTC, JessFreak reviewed
![image](https://github.com/fictadvisor/fictadvisor-api/assets/119421914/e63055cf-2863-42f6-8bfb-982486669de1)
add description

2023-09-11 15:32 UTC, JessFreak approved these changes

2023-09-12 07:27 UTC, illiakroshka approved these changes

2023-09-12 08:02 UTC, fokaaas approved these changes

2023-09-12 08:03 UTC, merged