migration #714: add branch info for TelegramGroup:
fictadvisor/fictadvisor-api pull request #726
Opened 2023-09-11 16:04 UTC by JessFreak

- add branchId for TelegramGroup
- add WITH_BRANCHES for TelegramSource

closes #714

2023-09-12 18:34 UTC, fokaaas requested changes

2023-09-12 18:34 UTC, fokaaas commented on src/v2/api/services/TelegramGroupService.ts
> +    if (body.source === 'CHAT_WITH_THREADS' && !body.threadId) {
TelegramSource.CHAT_WITH_THREADS

2023-09-12 18:34 UTC, fokaaas commented on src/v2/api/services/TelegramGroupService.ts
> +      throw new DataMissingException();
ObjectIsRequiredException('Thread ID') will be better

2023-09-13 16:25 UTC, fokaaas approved these changes

2023-09-13 18:15 UTC, illiakroshka approved these changes

2023-09-13 19:58 UTC, merged