migration #736: moved auth tokens to the database
fictadvisor/fictadvisor-api pull request #741
Opened 2023-09-16 12:28 UTC by hoshion

- created new prisma models;
- removed maps from class;
- created include field in UserRepository;
- created DbUser;
- added DbUser to UserRepository;
- simplified DbStudent;
- changed in dtos telegram id to bigint;

closes #736

2023-09-16 18:14 UTC, fokaaas requested changes
It's better to create repositories for new entities

2023-09-16 19:01 UTC, hoshion commented
> It's better to create repositories for new entities

No. It's not a business entity

2023-09-17 19:17 UTC, f-ogoog commented on src/v2/api/services/AuthService.ts
> +  }
excessive enter

2023-09-18 07:22 UTC, f-ogoog approved these changes

2023-09-18 14:59 UTC, fokaaas approved these changes

2023-09-18 14:59 UTC, merged