enhancement #729: added logging of students verification by captain
fictadvisor/fictadvisor-api pull request #742
Opened 2023-09-16 12:55 UTC by ArtemLyah

- added logging message

closes #729

2023-09-16 18:58 UTC, SharpDevOps10 requested changes

2023-09-16 18:58 UTC, SharpDevOps10 commented on src/v2/api/services/UserService.ts
> +
Get rid of redundant variables. It is better to rewrite it: 
```ts
const { group: { code }, firstName, lastName } = user.student;
```

2023-09-16 19:21 UTC, SharpDevOps10 approved these changes

2023-09-16 20:14 UTC, JessFreak approved these changes

2023-09-17 10:08 UTC, fokaaas approved these changes

2023-09-17 10:08 UTC, merged