enhancement #747: add sorting of students by last name
fictadvisor/fictadvisor-api pull request #748
Opened 2023-09-22 13:09 UTC by ArtemLyah

- created GroupStudentsQueryDTO
- added sorting students by last name
- added exception messages to swagger

closes #747

2023-09-26 18:52 UTC, fokaaas approved these changes

2023-09-26 18:52 UTC, fokaaas commented on src/v2/api/controllers/GroupController.ts
> +    `,
redundant line feed

2023-09-28 13:37 UTC, illiakroshka approved these changes

2023-09-28 13:38 UTC, illiakroshka requested changes

2023-09-28 13:38 UTC, illiakroshka commented on src/v2/api/controllers/GroupController.ts
>      InvalidGroupIdException:
Change the name of exeption 
![image](https://github.com/fictadvisor/fictadvisor-api/assets/116638814/26e5608f-12df-45a5-8cca-4208612012d8)

2023-09-29 14:26 UTC, illiakroshka approved these changes

2023-09-30 08:18 UTC, merged