feature #745: implemented endpoint for exporting the list of students
fictadvisor/fictadvisor-api pull request #749
Opened 2023-09-25 16:24 UTC by f-ogoog

- implemented endpoint for exporting the list of students
- added documentation
- added StudentWithContactsData

closes #745

2023-09-25 20:23 UTC, SharpDevOps10 approved these changes

2023-09-26 18:48 UTC, fokaaas requested changes

2023-09-26 18:48 UTC, fokaaas commented on src/v2/utils/files/FileService.ts
> +    setTimeout(() => fs.unlinkSync(path), HOUR);
set 15 minutes

2023-09-26 18:48 UTC, fokaaas commented on src/v2/utils/files/FileService.ts
> +    return resolve(process.env.BASE_URL, join('lists', fileName));
you have to generate link depending on prod or dev

2023-09-26 18:48 UTC, fokaaas commented on src/v2/api/controllers/GroupController.ts
> +  @ApiOkResponse()
you should return object with url

2023-09-27 17:41 UTC, fokaaas approved these changes

2023-09-27 17:41 UTC, merged