enhancement #750: Improved updating avatar:
fictadvisor/fictadvisor-api pull request #758
Opened 2023-09-27 13:42 UTC by JessFreak

- created FileService.getPathFromLink
- created FileService.checkFileExist
- created FileService.deleteFile
- created UserRepository.findMany
- fixed Swagger documentation

closes #750

2023-09-27 17:33 UTC, f-ogoog approved these changes

2023-09-29 14:58 UTC, ArtemLyah commented
![image](https://github.com/fictadvisor/fictadvisor-api/assets/63953579/29963357-49f3-4036-931e-2f902859b935)
Use this documentation style if swagger:
![image](https://github.com/fictadvisor/fictadvisor-api/assets/63953579/0a590d83-1d9a-4a65-ac85-2afd6b966a91)

2023-09-29 17:13 UTC, ArtemLyah approved these changes

2023-09-30 08:16 UTC, fokaaas requested changes

2023-09-30 08:16 UTC, fokaaas commented on src/v2/utils/files/FileService.ts
> +  async checkAvatarExist (avatar: string) {
Abstract this method, its task will simply check existence of files depending on whether they are private or static

2023-09-30 08:16 UTC, fokaaas commented on src/v2/utils/files/FileService.ts
> +      await fs.promises.access(filePath);
Use fs.existsSync

2023-09-30 08:16 UTC, fokaaas commented on src/v2/utils/files/FileService.ts
> +  async deleteAvatar (avatar: string) {
Abstract this method, its task will simply delete files depending on whether they are private or static

2023-10-03 09:18 UTC, fokaaas approved these changes

2023-10-03 09:23 UTC, merged