enhancement #744: Automated index calculation
fictadvisor/fictadvisor-api pull request #760
Opened 2023-09-29 11:46 UTC by kropli

- added updateEventInfo method
- updated parsePair method

closes #744

2023-09-29 16:08 UTC, SharpDevOps10 requested changes

2023-09-29 16:08 UTC, SharpDevOps10 commented on src/v2/utils/parser/ScheduleParser.ts
> +              endOfEvent, Period.EVERY_FORTNIGHT)) + 1,
Here you can use `weeksCountFortnight`

2023-09-29 16:08 UTC, SharpDevOps10 commented on src/v2/utils/parser/ScheduleParser.ts
> +            data: this.getIndexesForEventInfo(0, await this.getWeeksCount(endOfEvent, Period.EVERY_FORTNIGHT)),
You had better create a variable `weeksCountFortnight`, because you used **getWeeksCount** method twice

2023-09-30 07:53 UTC, SharpDevOps10 approved these changes

2023-10-03 22:23 UTC, PavloVlasiuk approved these changes

2023-10-05 09:43 UTC, fokaaas requested changes

2023-10-05 09:43 UTC, fokaaas commented on src/v2/utils/parser/ScheduleParser.ts
> +      await this.eventRepository.updateById(event.id, {
It is not logical, you check if event exists, but take it Id

2023-10-05 09:43 UTC, fokaaas commented on src/v2/utils/parser/ScheduleParser.ts
> +            data: this.getIndexesForEventInfo(weeksCountFortnight + 1, await this.getWeeksCount(endOfEvent, Period.EVERY_WEEK)),
declare variable to call function

2023-10-09 19:12 UTC, SharpDevOps10 approved these changes

2023-10-12 09:31 UTC, PavloVlasiuk approved these changes

2023-10-12 21:04 UTC, fokaaas approved these changes

2023-10-12 21:04 UTC, merged