feature #746: Add ability to leave group
fictadvisor/fictadvisor-api pull request #762
Opened 2023-09-30 20:39 UTC by Ksrebniukk

- changed the student's state to DECLINED and removed all roles from him
- added documentation

closes #746

2023-10-06 14:57 UTC, kropli requested changes

2023-10-06 14:57 UTC, kropli commented on src/v2/api/services/GroupService.ts
> +        userId: userId,
You can simplify this row just by typing "userId," instead of "userId: userId,"

2023-10-06 14:57 UTC, kropli commented on src/v2/security/PERMISSION.ts
> +  GROUP_LEAVE = 'groups.$groupId.leave',
it’s better to name constant as `GROUPS_$GROUPID_LEAVE` so it will match the template

2023-10-06 21:36 UTC, kropli approved these changes

2023-10-07 13:14 UTC, JessFreak requested changes
Also the resposne from endoint is not the same as in swagger. Fix it.

2023-10-07 13:14 UTC, JessFreak commented on src/v2/api/controllers/GroupController.ts
> +  @Patch('/:groupId/remove')
change to leave

2023-10-07 13:14 UTC, JessFreak commented on src/v2/api/controllers/GroupController.ts
> +  async leveGroup (
typo in leaveGroup

2023-10-07 13:14 UTC, JessFreak commented on src/v2/api/services/GroupService.ts
> +    return this.studentRepository.update({
use updateById

2023-10-12 06:35 UTC, JessFreak requested changes
![image](https://github.com/fictadvisor/fictadvisor-api/assets/119421914/5f7bbe4b-1967-4e11-ab54-77625aee8305)

it should not set this parameter to DECLINED

2023-10-12 06:42 UTC, JessFreak requested changes

2023-10-12 06:42 UTC, JessFreak commented on src/v2/api/controllers/GroupController.ts
> +  })
add more description in the documentation as in new issues

2023-10-14 18:07 UTC, JessFreak requested changes

2023-10-14 18:07 UTC, JessFreak commented on src/v2/api/services/GroupService.ts
> +            studentId: studentId,
simplify to 
studentId,

2023-10-14 18:19 UTC, JessFreak requested changes

2023-10-14 18:19 UTC, JessFreak commented on src/v2/api/controllers/GroupController.ts
> +  @Patch('/:groupId/leave')
add UnauthorizedException

2023-10-15 11:20 UTC, JessFreak requested changes

2023-10-15 11:20 UTC, JessFreak commented on src/v2/api/services/GroupService.ts
> +    if (student.state !== State.APPROVED) throw new NotApprovedException();
![image](https://github.com/fictadvisor/fictadvisor-api/assets/119421914/8267dfa9-f807-431f-b12c-143cbf9ea344)
![image](https://github.com/fictadvisor/fictadvisor-api/assets/119421914/6dcbd4c0-1b82-438b-81bf-6ac5365aa26c)

undocumented exception

2023-10-15 11:48 UTC, JessFreak approved these changes

2023-10-15 13:51 UTC, fokaaas requested changes

2023-10-15 13:51 UTC, fokaaas commented on src/v2/api/services/GroupService.ts
> +    await this.userService.getGroupRole(studentId);
Unnecessary call :)

2023-10-15 14:49 UTC, fokaaas approved these changes

2023-10-15 15:30 UTC, merged