documentation #765: added documentation to user endpoints
fictadvisor/fictadvisor-api pull request #777
Opened 2023-10-04 19:30 UTC by ArtemLyah

- added documentation to verify
- added documentation to verifySuperhero
- added documentation to requestNewGroup
- added documentation to createSuperhero
- added documentation to getSelective
- added documentation to getSelectiveBySemesters

closes #765

2023-10-05 13:31 UTC, fokaaas requested changes
You also need to add summary to each endpoint, but so that it doesn't erase description

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
> +  @Access(PERMISSION.USERS_$USERID_VERIFY_STUDENT, TelegramGuard)
remove permission

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
>    @Patch('/:userId/verifySuperhero')
add @ApiUnauthorizedResponse

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
> +  @Access(PERMISSION.USERS_$USERID_VERIFY_SUPERHERO, TelegramGuard)
remove permission

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
> +  @Patch('/:userId/requestNewGroup')
add @ApiUnauthorizedResponse

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
> +  @ApiOkResponse()
where?

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
>    @Post('/:userId/superhero')
add @ApiUnauthorizedResponse

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
>    @Get('/:userId/selective')
add @ApiUnauthorizedResponse

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
> +  @Get('/:userId/selectiveBySemesters')
add @ApiUnauthorizedResponse

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/dtos/ApproveDTO.ts
> +    description: 'whether the student is captain or not',
Capitalize

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/dtos/ApproveDTO.ts
> +    description: 'state for student verification',
Capitalize

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/dtos/UpdateSuperheroDTO.ts
> +    state?: State;
add default value

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/responses/GroupResponse.ts
> +    description: 'State for the student in group: APPROVED, PENDING, DECLINED',
don't specify values in the description, enum does it

2023-10-05 13:31 UTC, fokaaas commented on src/v2/api/responses/StudentResponse.ts
> +    description: 'State for the student: APPROVED, PENDING, DECLINED',
don't specify values in the description, enum does it

2023-10-05 13:31 UTC, fokaaas commented on src/v2/security/PERMISSION.ts
> +  USERS_$USERID_VERIFY_SUPERHERO = 'users.$userId.verifySuperhero',
remove it

2023-10-06 14:02 UTC, fokaaas approved these changes

2023-10-08 15:47 UTC, Ksrebniukk commented on src/v2/api/controllers/UserController.ts
> +    summary: 'Verify student to be a superhero',
the query description is the same as in the previous one

2023-10-09 11:08 UTC, Ksrebniukk commented on src/v2/api/controllers/UserController.ts
> +    type: StudentsResponse,
This is wrong. Print the another answer
![image](https://github.com/fictadvisor/fictadvisor-api/assets/104054772/90b3d187-190a-4a21-a1c4-e3d0677d1142)

2023-10-09 17:50 UTC, Ksrebniukk approved these changes

2023-10-10 07:33 UTC, merged