feature #751: added ability to delete avatars
fictadvisor/fictadvisor-api pull request #782
Opened 2023-10-06 18:30 UTC by SharpDevOps10

- added deleteAvatar method
- moved check logic
- added permission

closes #751

2023-10-06 19:00 UTC, fokaaas requested changes

2023-10-06 19:00 UTC, fokaaas commented on src/v2/api/controllers/UserController.ts
> +      Data were not found`,
Where?

2023-10-07 04:53 UTC, fokaaas approved these changes

2023-10-07 12:53 UTC, JessFreak approved these changes

2023-10-08 06:32 UTC, merged