enhancement #771: Improved and merged endpoints for captain changing:
fictadvisor/fictadvisor-api pull request #790
Opened 2023-10-11 14:59 UTC by JessFreak

- deleted transferCaptain in GroupController
- moved permission to switchCaptain
- created changeRole in UserService

closes #771

2023-10-12 20:48 UTC, fokaaas requested changes
Also, your endpoint should return updated captain

2023-10-12 20:48 UTC, fokaaas commented on src/v2/api/services/GroupService.ts
> +    const { id: oldCaptainId } = await this.getCaptain(groupId) || { id: null };
it would be better to just remove destructuring

2023-10-12 20:48 UTC, fokaaas commented on src/v2/api/services/UserService.ts
> +    const userRole = await this.getGroupRoleDB(studentId);
wrong naming, it's group role

2023-10-13 14:49 UTC, fokaaas approved these changes

2023-10-15 10:18 UTC, illiakroshka commented on src/v2/api/controllers/GroupController.ts
> +    permissions: [PERMISSION.GROUPS_CAPTAIN_SWITCH, PERMISSION.GROUPS_$GROUPID_TRANSFER],
Endpoint must work when user has 1 of these 2 permissions. But it works only when user has 2 permissions

2023-10-15 12:21 UTC, illiakroshka approved these changes

2023-10-15 13:57 UTC, merged