migration #779: added displayName field
fictadvisor/fictadvisor-api pull request #793
Opened 2023-10-12 15:49 UTC by SharpDevOps10

- added displayName for Role endpoints

closes #779

2023-10-13 14:41 UTC, fokaaas requested changes
Also you should add documentation to endpoints as in new issues

2023-10-13 14:41 UTC, fokaaas commented on prisma/schema.prisma
> +  displayName String?
```@map("display_name")```

2023-10-13 21:45 UTC, fokaaas approved these changes

2023-10-18 14:38 UTC, PavloVlasiuk requested changes

2023-10-18 14:38 UTC, PavloVlasiuk commented on src/v2/api/controllers/RoleController.ts
>    @Post('/:roleId/grants')
update the documentation for the last two endpoints (post and get '/:roleId/grants')

2023-10-18 15:16 UTC, PavloVlasiuk approved these changes

2023-11-01 06:00 UTC, fokaaas approved these changes

2023-11-02 16:54 UTC, merged