enhancement #789: added the ability to get selective discipline for t…
fictadvisor/fictadvisor-api pull request #795
Opened 2023-10-13 12:51 UTC by f-ogoog

…elegram

- added the ability to get selective discipline for telegram
- changed 3 endpoints for telegram

closes #789

2023-10-14 16:18 UTC, SharpDevOps10 requested changes

2023-10-14 16:18 UTC, SharpDevOps10 commented on src/v2/api/services/ScheduleService.ts
> +  async getGroupEventsForTelegram (groupId: string, week: number, userId) {
Add type for `userId`

2023-11-02 12:23 UTC, SharpDevOps10 approved these changes

2023-11-02 12:23 UTC, SharpDevOps10 commented on src/v2/api/responses/DisciplineTypeResponse.ts
> +    description: 'Discipline`s id',
Rename to: `Discipline\'s id`

2023-11-02 12:23 UTC, SharpDevOps10 commented on src/v2/api/responses/MainEventInfoResponse.ts
> +  })
* Rename to: `'Event\'s id'`
* Rename to: `'Event\'s name'`

2023-11-02 12:23 UTC, SharpDevOps10 commented on src/v2/api/responses/TelegramGeneralEventInfoResponse.ts
> +    description: 'Event`s url',
Rename to: `Event\'s url`

2023-11-02 19:17 UTC, JessFreak requested changes
endpoint returns incorrect selective disciplines

2023-11-03 05:56 UTC, fokaaas approved these changes

2023-11-03 05:57 UTC, merged