documentation #799: updated swagger doc for role endpoints:
fictadvisor/fictadvisor-api pull request #804
Opened 2023-10-15 13:18 UTC by fujivara

- GET /v2/roles/{roleId}
- DELETE /v2/roles/{roleId}
- PATCH /v2/roles/{roleId}
- GET /v2/roles
- POST /v2/roles

closes #799

2023-10-16 10:24 UTC, f-ogoog approved these changes

2023-10-16 18:09 UTC, Yakorrr approved these changes

2023-11-01 05:55 UTC, fokaaas requested changes

2023-11-01 05:55 UTC, fokaaas commented on src/v2/api/responses/RoleResponse.ts
>      grants: MappedGrant[];
Also add description to MappedGrant

2023-11-01 05:55 UTC, fokaaas commented on src/v2/api/dtos/CreateRoleWithGrantsDTO.ts
>    @Type(() => CreateGrantDTO)
Add description to CreateGrantDTO and parentId

2023-11-01 14:23 UTC, fokaaas approved these changes

2023-11-01 14:24 UTC, merged