documentation #801: updated swagger doc for Poll endpoints:
fictadvisor/fictadvisor-api pull request #807
Opened 2023-10-15 15:43 UTC by Dmutre

- POST v2/poll/questions
- GET v2/poll/teachers/{userId}
- DELETE v2/poll/questions/{questionId}
- PATCH v2/poll/questions/{questionId}
- GET v2/poll/questions/{questionId}
- POST v2/poll/questions/{questionId}/roles
- DELETE v2/poll//questions/{questionId}/roles/{role}

closes #801

2023-10-16 19:29 UTC, SharpDevOps10 requested changes
* If you describe class that extends another => you should describe `extended` class as well.
* In some cases, you should change `InvalidEntityIdException` argument. The argument should begin with a capital letter (it concerns QuestionByRoleAndIdPipe, QuestionByIdPipe)

2023-10-16 19:29 UTC, SharpDevOps10 commented on src/v2/api/controllers/PollController.ts
> +    summary: "Request to get a question by ID",
ESLint: Strings must use singlequote. (quotes)

2023-10-16 19:29 UTC, SharpDevOps10 commented on src/v2/api/controllers/PollController.ts
> +      question with such id is not found`,
Upper letter (`Question`), not `question`

2023-10-16 19:29 UTC, SharpDevOps10 commented on src/v2/api/controllers/PollController.ts
> +      Question with such id is not found`,
* Don't split `InvalidBodyException` into separate parts. There should be only one `InvalidBodyException`  and under it you should write name of your exception, e.g `Visibility cannot be empty`
* Rename: `Role cannot be empty` `Visibility cannot be empty`

2023-10-16 19:29 UTC, SharpDevOps10 commented on src/v2/api/controllers/PollController.ts
> +    name: "questionId",
ESLint: Strings must use singlequote. (quotes)

2023-10-16 19:29 UTC, SharpDevOps10 commented on src/v2/api/controllers/PollController.ts
> +    description: 'Id of question in wich you want to create role',
Rename: `Id of the question to which you want to attach the role`

2023-10-16 19:29 UTC, SharpDevOps10 commented on src/v2/api/controllers/PollController.ts
> +    summary: 'Request to create role in question',
Rename: `Give the role to the question by id`

2023-10-16 19:29 UTC, SharpDevOps10 commented on src/v2/api/controllers/PollController.ts
> +  })
Add description to `questionId` and `role`

2023-10-16 19:29 UTC, SharpDevOps10 commented on src/v2/api/controllers/PollController.ts
> +    permissions: PERMISSION.QUESTIONS_ROLES_DELETE,
Wrong summary. This endpoint does not delete the question

2023-11-02 16:52 UTC, fokaaas requested changes

2023-11-02 16:52 UTC, fokaaas commented on src/v2/api/dtos/CreateQuestionWithRolesDTO.ts
>        type: [CreateQuestionRoleDTO],
You must also describe the class from which you extend (CreateQuestionDTO).

2023-11-02 16:52 UTC, fokaaas commented on src/v2/api/responses/QuestionWithRolesResponse.ts
>  export class QuestionWithRolesResponse extends QuestionResponse {
You must also describe the class from which you extend (QuestionResponse).

2023-11-02 16:52 UTC, fokaaas commented on src/v2/api/responses/PollDisciplineTeachersResponse.ts
>      teachers: DisciplineTeachers[];
Also describe DisciplineReachers & Subject

2023-11-02 16:52 UTC, fokaaas commented on src/v2/api/dtos/CreateQuestionRoleDTO.ts
> +    description: 'An enum of teacher\'s',
teacher roles)

2023-11-03 17:21 UTC, fokaaas approved these changes

2023-11-03 17:21 UTC, merged