feature #773: Created endpoint for updating cathedras
fictadvisor/fictadvisor-api pull request #810
Opened 2023-10-20 06:51 UTC by JessFreak

- created CathedraMapper
- created DbCathedra
- created update methods in Cathedra Repository and Service
- created UpdateCathedraDTO
- changed and added Swagger documentation

closes #773

2023-11-01 14:36 UTC, illiakroshka requested changes

2023-11-01 14:36 UTC, illiakroshka commented on src/v2/api/dtos/CreateCathedraDTO.ts
> +    description: 'The name of the cathedra',
Maybe here better to write "The abbreviation of the cathedra"

2023-11-02 07:37 UTC, illiakroshka approved these changes

2023-11-03 17:53 UTC, ArtemLyah approved these changes

2023-11-05 09:03 UTC, fokaaas requested changes

2023-11-05 09:03 UTC, fokaaas commented on src/v2/modules/CathedraModule.ts
> +  exports: [CathedraService, CathedraMapper],
You have to add it to mapper module

2023-11-05 09:03 UTC, fokaaas commented on src/v2/modules/TeacherModule.ts
> +  exports: [TeacherService, DisciplineTeacherService, TeacherMapper],
You have to add it to mapper module

2023-11-05 09:03 UTC, fokaaas commented on src/v2/api/dtos/CreateCathedraDTO.ts
> +  @IsNotEmpty(validationOptionsMsg('Cathedra name can not be empty'))
It's optional

2023-11-05 20:32 UTC, fokaaas approved these changes

2023-11-05 20:32 UTC, merged