feature #772: Created endpoint for receiving all cathedras
fictadvisor/fictadvisor-api pull request #814
Opened 2023-10-30 11:57 UTC by illiakroshka

- Created DbCathedra
- Created findMany and count methods in repository
- Created getAll method in the service
- Created QueryAllCathedrasDTO
- Implemented sorting(name, abbreviation),order (asc, desc), search (name, abbreviation)
- Added Swagger documentation

closes #772

2023-11-02 17:27 UTC, f-ogoog commented on src/v2/database/repositories/CathedraRepository.ts
> +    data: Prisma.CathedraFindManyArgs,
needless enter

2023-11-03 19:27 UTC, f-ogoog requested changes

2023-11-06 18:58 UTC, f-ogoog approved these changes

2023-11-10 14:22 UTC, Yakorrr approved these changes

2023-11-10 17:31 UTC, fokaaas requested changes
Check qodana warning

2023-11-10 18:58 UTC, fokaaas requested changes
Pls simply return the number of teachers instead of the objects

2023-11-10 18:58 UTC, fokaaas commented on src/v2/api/controllers/CathedraController.ts
> +  @Access(PERMISSION.CATHEDRAS_CREATE)
Add it into ApiEndoint

2023-11-14 16:52 UTC, Dmutre approved these changes
QA test is complited

2023-11-14 20:49 UTC, fokaaas approved these changes

2023-11-14 20:50 UTC, merged