feature #833: created an endpoint for bot to create events
fictadvisor/fictadvisor-api pull request #838
Opened 2023-11-07 16:40 UTC by ArtemLyah

- created endpoint createSimpleTelegramEvent that creates simple version of an event
- created mapper method for the endpoint
- created dto for the endpoint
- created respoce for the endpoint
- added documentation for the endpoint

closses #833

2023-11-10 11:29 UTC, f-ogoog requested changes

2023-11-10 11:29 UTC, f-ogoog commented on src/v2/mappers/ScheduleMapper.ts
> +      eventInfo: event.eventInfo[0]?.description || null,
now get endpoints return events without eventInfo, so you need improve 3 endpoints for get day/week/fortnight events and add field eventInfo

I think you can just add this field in getTelegramEvents

2023-11-10 11:29 UTC, f-ogoog commented on src/v2/mappers/ScheduleMapper.ts
> +      url: event.url || null,
needless null

2023-11-12 15:55 UTC, f-ogoog requested changes

2023-11-12 15:55 UTC, f-ogoog commented on src/v2/mappers/ScheduleMapper.ts
> +      url: event.url,
you should add eventInfo and use this finction is getTelegramEvents

2023-11-12 15:55 UTC, f-ogoog commented on src/v2/api/responses/EventResponse.ts
> +export class SimpleEventResponse {
needless class, you should use TelegramEventInfoResponse

2023-11-14 15:41 UTC, f-ogoog approved these changes

2023-11-15 11:26 UTC, illiakroshka requested changes
The example of responce contains "disciplineType"
![image](https://github.com/fictadvisor/fictadvisor-api/assets/116638814/95f097d2-1c4a-41fe-8aad-4fe75ac63b2f)

But actual responce doen't have it 
![image](https://github.com/fictadvisor/fictadvisor-api/assets/116638814/fc0dd76f-9080-4ae9-a0be-9c197edd61a4)

2023-11-15 11:45 UTC, illiakroshka approved these changes

2023-11-18 21:34 UTC, fokaaas approved these changes

2023-11-23 15:57 UTC, merged