documentation #798: updated swagger doc for group endpoints
fictadvisor/fictadvisor-api pull request #841
Opened 2023-11-09 09:25 UTC by fujivara

- DELETE /v2/groups/{groupId}
- GET /v2/groups/{groupId}/students
- GET /v2/groups/{groupId}/captain
- GET /v2/groups/{groupId}/disciplineTeachers
- GET /v2/groups/{groupId}/disciplines

closes #798

2023-11-10 14:51 UTC, kropli requested changes

2023-11-10 14:51 UTC, kropli commented on src/v2/api/controllers/GroupController.ts
> +
No space is required between exceptions

2023-11-10 14:51 UTC, kropli commented on src/v2/api/controllers/GroupController.ts
> +
No space is required between exceptions

2023-11-11 14:49 UTC, kropli approved these changes

2023-11-11 15:47 UTC, aim4ik11 requested changes
In teacherresponse change optional fields with required ones
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/7e53e09d-0ac1-4944-954e-09bcf4566909)

2023-11-11 15:47 UTC, aim4ik11 commented on src/v2/api/responses/StudentResponse.ts
>    @ApiProperty({
Remove questionmark near telegramId

2023-11-11 15:47 UTC, aim4ik11 commented on src/v2/api/controllers/GroupController.ts
> +      NoPermissionException:
Add unauthorized exception
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/2f6d07d7-2396-4e08-9409-d8a12cdd0462)

2023-11-11 15:47 UTC, aim4ik11 commented on src/v2/api/responses/StudentResponse.ts
>    @ApiPropertyOptional({
Change decorator to ApiProperty (make a required field)

2023-11-11 15:47 UTC, aim4ik11 commented on src/v2/api/controllers/GroupController.ts
> +    AbsenceOfCaptainException:
Place enter between 2 different exceptions

2023-11-11 15:47 UTC, aim4ik11 commented on src/v2/api/controllers/GroupController.ts
> +    description: 'Id of the group to get the captain from',
Add required: true

2023-11-11 15:53 UTC, aim4ik11 requested changes

2023-11-11 15:53 UTC, aim4ik11 commented on src/v2/api/controllers/GroupController.ts
>      DataMissingException:
Add enter between exceptions

2023-11-12 08:25 UTC, aim4ik11 requested changes

2023-11-12 08:25 UTC, aim4ik11 commented on src/v2/api/controllers/GroupController.ts
> +    description: 'Id of the group to get the discipline teachers from',
Add required true

2023-11-12 08:25 UTC, aim4ik11 commented on src/v2/api/controllers/GroupController.ts
> +    description: 'Id of the group to get the disciplines from',
Add required true

2023-11-12 13:30 UTC, aim4ik11 approved these changes

2023-11-13 10:22 UTC, fokaaas approved these changes

2023-11-13 10:22 UTC, merged