documentation #816: updated swagger for permission and telegram group…
fictadvisor/fictadvisor-api pull request #847
Opened 2023-11-12 13:24 UTC by illiakroshka

…s endpoints

- POST /v2/permissions/check
- POST /v2/telegramGroups/{groupId}
- GET /v2/telegramGroups/{groupId}
- PATCH /v2/telegramGroups
- DELETE /v2/telegramGroups
- GET /v2/telegramGroups/telegram/{telegramId} closes #816

2023-11-13 10:18 UTC, JessFreak requested changes

2023-11-13 10:18 UTC, JessFreak commented on src/v2/api/controllers/PermissionController.ts
> +  })
add description

2023-11-13 10:18 UTC, JessFreak commented on src/v2/api/controllers/TelegramGroupController.ts
>    })
this endpoint returns information for several telegramGroups, not just one

2023-11-13 20:20 UTC, JessFreak approved these changes

2023-11-14 09:16 UTC, aim4ik11 requested changes
Write documentation and add descriptions to CheckPermissionsDTO and CheckPermissionsResponse
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/0e0a1645-10f1-46a8-b42f-a60d7cc39dec)

2023-11-14 09:17 UTC, aim4ik11 requested changes
Write documentation and add descriptions to CreateTelegramGroupDTO
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/839a954e-d478-4343-bbf4-515e8f0400ef)

2023-11-14 09:18 UTC, aim4ik11 requested changes
Write documentation and add descriptions to TelegramGroupResponse
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/29f4073f-cad4-45d9-89aa-2527b6f27c5f)

2023-11-14 09:18 UTC, aim4ik11 requested changes
Write documentation and add descriptions to TelegramGroupsResponse
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/8a7e554b-a8aa-4a33-9fe5-39d19d93be13)

2023-11-14 09:19 UTC, aim4ik11 requested changes
Write documentation and add descriptions to UpdateTelegramGroupDTO
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/5e0b8546-c286-4c36-824c-41510ce51cee)

2023-11-14 09:21 UTC, aim4ik11 requested changes
Write documentation and add descriptions to TelegramGroupsByTelegramIdResponse, TelegramGroupByTelegramIdResponse, GroupResponse
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/a1573279-bc37-4cc2-94cd-bbd850a9e67a)

2023-11-19 13:11 UTC, aim4ik11 requested changes
Response body in permissions/check does not match with example value response
![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/9ac45553-7c3d-42fc-8c69-61d55998cea8)

2023-11-19 13:28 UTC, aim4ik11 requested changes
Fix indent near DataNotFoundException: in update group

![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/705df2f6-62f0-40c0-bbb4-52366141ac15)

2023-11-19 13:28 UTC, aim4ik11 commented on src/v2/api/responses/TelegramGroupByTelegramIdResponse.ts
>    })
Add description to response

2023-11-19 14:45 UTC, aim4ik11 requested changes
Change decorators order so that first goes auth, created response and then exception responses

![image](https://github.com/fictadvisor/fictadvisor-api/assets/135731067/333955b5-37f5-4330-b03e-fb5c04d3b796)

2023-11-19 14:46 UTC, aim4ik11 requested changes
Set correct order in all endpoint in telegramgroupcontroller

2023-11-19 16:46 UTC, fokaaas requested changes

2023-11-19 16:46 UTC, fokaaas commented on src/v2/api/controllers/TelegramGroupController.ts
>    @ApiOkResponse()
The deleted group should be here

2023-11-19 17:04 UTC, aim4ik11 approved these changes

2023-11-19 17:04 UTC, aim4ik11 commented on src/v2/api/controllers/TelegramGroupController.ts
> +  @UseGuards(TelegramGuard)
Remove use guards, api endpoint guards is enough

2023-11-19 17:04 UTC, aim4ik11 commented on src/v2/api/controllers/TelegramGroupController.ts
> +  @UseGuards(TelegramGuard)
Remove useguards

2023-11-19 18:55 UTC, fokaaas approved these changes

2023-11-19 19:01 UTC, merged