enhancement #849 improved endpoint to get all teachers:
fictadvisor/fictadvisor-api pull request #852
Opened 2023-11-13 18:33 UTC by aim4ik11

-added teacher roles
-added teacher cathedras

closes #849

2023-11-19 13:16 UTC, kropli approved these changes

2023-11-22 11:37 UTC, ArtemLyah approved these changes

2023-11-27 15:05 UTC, fokaaas requested changes
There are certain remarks, the endpoint does not quite match the design.
- you must have a multichoice for **cathedras**, i.e. an array of queries
- you must have a multichoice for **teacher roles**

![image](https://github.com/fictadvisor/fictadvisor-api/assets/114052215/2d3d0851-52c7-476e-bf56-85ce43a9ce3c)

**You can also extend from QueryAll**

2023-11-27 15:05 UTC, fokaaas commented on src/v2/database/entities/DbTeacher.ts
> +  }[];
```ts
cathedras: (TeachersOnCathedras & {
    cathedra: Cathedra,
  })[];
```

2023-11-27 15:05 UTC, fokaaas commented on src/v2/api/controllers/TeacherController.ts
> +  @Get()
Add ```@ApiEndpoint()```

2024-01-04 14:03 UTC, fokaaas requested changes

2024-01-04 14:03 UTC, fokaaas commented on src/v2/api/controllers/TeacherController.ts
>    @Post()
if you choose to describe the documentation for this endpoint, finish it by adding descriptions to the body

2024-01-04 14:03 UTC, fokaaas commented on src/v2/api/controllers/TeacherController.ts
>    @Patch('/:teacherId')
if you choose to describe the documentation for this endpoint, finish it by adding descriptions to the body

2024-01-04 14:03 UTC, fokaaas commented on src/v2/api/pipes/AllTeachersPipe.ts
> +    }
Transfer this logic to service or improve existing pipes

2024-01-04 14:03 UTC, fokaaas commented on src/v2/mappers/TeacherMapper.ts
> +  getTeacherCathedras (teacher: DbTeacher) : string[] {
Make this method private and add spaces

2024-01-04 20:19 UTC, aim4ik11 commented on src/v2/api/controllers/TeacherController.ts
>    @Post()
Polyak moment

2024-01-04 21:20 UTC, fokaaas approved these changes

2024-01-04 21:20 UTC, merged