feature #848: Created an endpoint for deleting disciplines
fictadvisor/fictadvisor-api pull request #854
Opened 2023-11-14 18:06 UTC by fujivara

- Created delete endpoint in DisciplineController
- Created deleteDiscipline method in DisciplineService
- Created deleteById method in DisciplineRepository
- Created getDiscipline method in DisciplineMapper

closes #848

2023-11-15 11:01 UTC, illiakroshka requested changes

2023-11-15 12:39 UTC, illiakroshka approved these changes

2023-11-19 11:25 UTC, PavloVlasiuk approved these changes

2023-11-23 16:51 UTC, fokaaas requested changes

2023-11-23 16:51 UTC, fokaaas commented on src/v2/database/repositories/DisciplineRepository.ts
> +  async deleteById (id: string): Promise<Discipline> {
Should be ```Promise<DbDiscipline>```

2023-11-23 16:51 UTC, fokaaas commented on src/v2/database/repositories/DisciplineRepository.ts
> +        id,
Add include

2023-11-23 16:51 UTC, fokaaas commented on src/v2/mappers/DisciplineMapper.ts
> +  }
Use getDisciplinesWithTeachers instead.

2023-11-27 17:53 UTC, fokaaas approved these changes

2023-11-27 17:57 UTC, merged