feature #842: Implemented an endpoint to receive all disciplines
fictadvisor/fictadvisor-api pull request #855
Opened 2023-11-15 19:06 UTC by JessFreak

- created getStrictSearch in DatabaseUtils
- created getAll in DisciplineController
- created getAll in DisciplineService
- created getDisciplinesForAdmin in DisciplineMapper
- created count in DisciplineRepository
- created DisciplineAdminResponse and DisciplinesResponse
- created QueryAllDisciplinesDTO
- created QueryAllDisciplinesPipe
- created ShortTeacherResponse

closes #842

2023-11-16 19:09 UTC, f-ogoog requested changes

2023-11-16 19:09 UTC, f-ogoog commented on src/v2/api/responses/DisciplineResponse.ts
> +    description: 'Group\' associated with the discipline',
needless \'

2023-11-16 19:09 UTC, f-ogoog commented on src/v2/api/responses/DisciplineResponse.ts
> +    description: 'Teacher\' associated with the discipline',
needless '

2023-11-16 19:09 UTC, f-ogoog commented on src/v2/api/services/DisciplineService.ts
> +    name: (name: string) => ({
rename parameter name to search

2023-11-16 19:09 UTC, f-ogoog commented on src/v2/api/services/DisciplineService.ts
> +      orderBy: this.DisciplineSorting[sort](order),
use this function in variable before put it in data

2023-11-16 19:09 UTC, f-ogoog commented on src/v2/database/repositories/DisciplineRepository.ts
> +    );
needless enters

2023-11-18 11:07 UTC, f-ogoog commented on src/v2/api/responses/DisciplineResponse.ts
> +    description: 'Group associated with the discipline',
add Type

2023-11-18 11:11 UTC, f-ogoog requested changes

2023-11-18 11:11 UTC, f-ogoog commented on src/v2/api/dtos/QueryAllDisciplinesDTO.ts
> +  })
add IsOptional

2023-11-18 11:27 UTC, f-ogoog approved these changes

2023-11-19 13:40 UTC, SharpDevOps10 requested changes
Also filtering using `semesters` does not work :(

2023-11-19 13:40 UTC, SharpDevOps10 commented on src/v2/api/responses/DisciplineResponse.ts
> +}
**Disciplines**, an array of objects, has `name` field. You missed it => add it to your response

2023-11-19 13:40 UTC, SharpDevOps10 commented on src/v2/api/dtos/QueryAllDisciplinesDTO.ts
> +    search?: string;
You've extended `QueryAllDTO` with `search` field => there is no need to add this filed to `QueryAllDisciplinesDTO`

2023-11-20 21:47 UTC, SharpDevOps10 approved these changes

2023-11-27 17:37 UTC, fokaaas requested changes
So, test it through axios and it will work :)

2023-11-27 17:37 UTC, fokaaas commented on src/v2/api/dtos/QueryAllDisciplinesDTO.ts
> +  })
Add ```@Type(() => QuerySemesterDTO)```

2024-01-09 09:52 UTC, fokaaas commented
closed as outdated

2024-01-09 09:52 UTC, closed without merging