enhancement #856: updated response body after receiving teacher's com…
fictadvisor/fictadvisor-api pull request #868
Opened 2023-11-21 09:16 UTC by illiakroshka

…ments

- Updated response body in question mapper
- Updated swagger doc for GET /teachers/:teacherId/comments

closes #856

2023-11-23 20:51 UTC, fokaaas requested changes

2023-11-23 20:51 UTC, fokaaas commented on src/v2/api/responses/PaginatedQuestionCommentsResponse.ts
>      year: string;
It's number

2023-11-24 16:29 UTC, fokaaas approved these changes

2023-11-28 17:00 UTC, Dmutre approved these changes
QA tests is complited, endpoints works and swagger doc is updated

2023-11-28 20:24 UTC, fokaaas approved these changes

2023-11-28 20:24 UTC, merged