feature #856: added ability to update comments
fictadvisor/fictadvisor-api pull request #870
Opened 2023-11-24 15:33 UTC by illiakroshka

- Created update in QuestionAnswerRepository
- Created updateComment in PollService
- Created PATCH teachers/comment/update endpoint
- Created UpdateCommentDTO
- Created UpdateCommentPipe
- Created InvalidTypeException
- Added permission
- Added Swagger documentation

closes #856

2023-11-24 16:19 UTC, fokaaas requested changes

2023-11-24 16:19 UTC, fokaaas commented on src/v2/security/PERMISSION.ts
> +  TEACHERS_COMMENT_UPDATE = 'teachers.comment.update',
disciplineTeachers.comment.update

2023-11-24 16:19 UTC, fokaaas commented on src/v2/api/responses/UpdatedCommentResponse.ts
> +}
It must be ```class Comment``` as response

2023-11-24 16:19 UTC, fokaaas commented on src/v2/api/controllers/DisciplineTeacherController.ts
> +  @Patch('/:disciplineTeacherId/update/comment')
Don't specify in the path what the HTTP methods specify. Remove ```update```

2023-11-24 16:19 UTC, fokaaas commented on src/v2/api/controllers/DisciplineTeacherController.ts
> +    const updatedComment = await this.pollService.updateComment(disciplineTeacherId, body);
Move logic to discipline teacher service.

2023-12-01 13:09 UTC, illiakroshka commented
It is not possible to have "comment" class in the responce because it doesn't return name of the discipline. That's why I created new custom UpdatedComment responce and also added question id there

2024-01-03 21:14 UTC, fokaaas requested changes

2024-01-03 21:14 UTC, fokaaas commented on src/v2/api/controllers/DisciplineTeacherController.ts
> +    permissions: PERMISSION.DISCIPLINE_TEACHERS_COMMENT_UPDATE,
just COMMENTS_UPDATE

2024-01-03 21:14 UTC, fokaaas commented on src/v2/api/dtos/UpdateCommentDTO.ts
> +  @IsNotEmpty()
add message

2024-01-03 21:14 UTC, fokaaas commented on src/v2/api/dtos/UpdateCommentDTO.ts
> +  @IsNotEmpty()
add message

2024-01-03 21:14 UTC, fokaaas commented on src/v2/api/dtos/UpdateCommentDTO.ts
> +  @IsNotEmpty()
add message

2024-01-03 21:14 UTC, fokaaas commented on src/v2/api/pipes/UpdateCommentPipe.ts
> +    }
it's better not to create a pipe, transfer the business logic to the service

2024-01-04 14:51 UTC, fokaaas approved these changes

2024-01-04 18:11 UTC, SharpDevOps10 requested changes
Also update `InvalidEntityIdException ('DisciplineTeacher')`

2024-01-04 18:11 UTC, SharpDevOps10 commented on src/v2/api/controllers/DisciplineTeacherController.ts
> +      DisciplineTeacherId should not be empty
Redundant exception  `DisciplineTeacherId should not be empty`

2024-01-04 18:11 UTC, SharpDevOps10 commented on src/v2/api/dtos/UpdateCommentDTO.ts
> +    comment: string;
validationOptionsMsg string parameter should start with a capital letter

2024-01-09 09:52 UTC, closed without merging

2024-01-09 09:52 UTC, fokaaas commented
closed as outdated