feature #862: Added the ability to get all users
fictadvisor/fictadvisor-api pull request #871
Opened 2023-11-24 21:23 UTC by dmykyr

- added users.get permission
- added getAll method in UserController
- added getAll method in UserMapper
- added getAll method in UserService
- added count method in UserRepository
- updated findMany method in userRepository
- created QueryAllUsersDTO and SortQAUParam
- created UsersResponse

closes #862

2023-11-24 22:26 UTC, f-ogoog requested changes

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/controllers/UserController.ts
> +    summary: 'Get information about each user',
i think it will be better write: Get all user for admin

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/dtos/SortQAUParam.ts
> +}
transfer this enum to QueryAllUsersDTO

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/dtos/QueryAllUsersDTO.ts
> +      enum: SortQARParam,
should be SortQAUParam

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/dtos/QueryAllUsersDTO.ts
> +      default: 'displayName',
SortQAUParam doesn't have this field

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/dtos/QueryAllUsersDTO.ts
> +      enum: State,
add type

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/dtos/QueryAllUsersDTO.ts
> +      state?: State[];
now you don't validate parameter, you should add @Validate or add validation in Pipe

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/dtos/QueryAllUsersDTO.ts
> +    @Transform(({ value }) => value.split(','))
you can receive array in query so you don't need receive string

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/dtos/QueryAllUsersDTO.ts
> +export class QueryAllUsersDTO extends QueryAllDTO {
add search and write in description by which fields you serching

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/responses/UsersResponse.ts
> +      description: 'User\'s telegram username',
why telegram? it is fa username

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/responses/UsersResponse.ts
> +      data: UserForGetAllResponse[];
should be users

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/services/UserService.ts
> +    const search = DatabaseUtils.getSearch(query, 'username');
you should search also by email

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/services/UserService.ts
> +        state: query.state? {
query.state it's array so condition will be always true

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/database/repositories/UserRepository.ts
> +    console.log(args.where.state, 'args');                                         // ---------------LOG HERE!!!!!!!!!!!!!!-----------------
mmm huita

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/services/UserService.ts
> +    return {
transfer it to the controller

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/database/repositories/UserRepository.ts
> +      data,
write in 1 line

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/mappers/UserMapper.ts
> +    );
needless enter

2023-11-24 22:26 UTC, f-ogoog commented on src/v2/api/dtos/QueryAllUsersDTO.ts
> +
needless enter

2023-11-25 21:57 UTC, f-ogoog commented on src/v2/api/controllers/UserController.ts
> +      State must be an enum
this message doesn't exist

2023-11-26 21:01 UTC, f-ogoog approved these changes

2023-11-29 13:48 UTC, fujivara requested changes

2023-11-29 13:48 UTC, fujivara commented on src/v2/api/services/UserService.ts
> +        state: query.state.length !== 0 ? {
Since state is optional, check if there is a length property on it.

2023-11-30 08:54 UTC, fujivara approved these changes

2024-01-09 09:52 UTC, fokaaas commented
closed as outdated

2024-01-09 09:52 UTC, closed without merging