feature #869: create endpoint for user creation
fictadvisor/fictadvisor-api pull request #875
Opened 2023-11-28 19:10 UTC by ArtemLyah

- created createUser endpoint
- created UserByAdminDTO for the endpoint
- added admin PERMISSION

closes #869

2023-12-02 17:26 UTC, PavloVlasiuk requested changes

2023-12-02 17:26 UTC, PavloVlasiuk commented on src/v2/api/controllers/UserController.ts
> +      await this.userService.createUserByAdmin(body)
create an intermediate variable for data that are returned by createUserByAdmin method and then pass it to getUser method

2023-12-02 17:26 UTC, PavloVlasiuk commented on src/v2/api/controllers/UserController.ts
> +    type: UserResponse,
make avatar an optional field in UserResponse class

2024-01-21 19:27 UTC, fokaaas commented
closed as outdated

2024-01-21 19:27 UTC, closed without merging