enhancement #861: created the endpoint for receiving all students
fictadvisor/fictadvisor-api pull request #876
Opened 2023-11-28 19:23 UTC by f-ogoog

- created the endpoint for receiving all students
- added AllStudentsPipe.ts, SimpleStudentResponse, QueryAllStudentDTO.ts

closes #861

2023-11-28 19:49 UTC, ArtemLyah commented on src/v2/api/dtos/QueryAllStudentDTO.ts
> +  @IsIn([SortQGSParam.FIRST_NAME, SortQGSParam.LAST_NAME, SortQGSParam.MIDDLE_NAME], validationOptionsMsg('Sort should be an enum'))
here it's better to use IsEnum

2023-11-28 19:55 UTC, ArtemLyah commented on src/v2/api/dtos/QueryAllStudentDTO.ts
> +  @IsOptional(validationOptionsMsg('Groups should be an array'))
it's better to use the validationMessage in IsArray

2023-11-28 19:56 UTC, ArtemLyah commented on src/v2/api/dtos/QueryAllStudentDTO.ts
> +  @IsEnum([RoleName.STUDENT, RoleName.MODERATOR, RoleName.CAPTAIN], { each: true, message: 'Each element of roles should be an enum' })
make this row more readable

2023-11-28 20:04 UTC, ArtemLyah commented on src/v2/api/responses/StudentResponse.ts
> +    enum: [RoleName.STUDENT, RoleName.MODERATOR, RoleName.CAPTAIN],
also use new enum there

2023-11-28 20:19 UTC, ArtemLyah commented on src/v2/database/DatabaseUtils.ts
> +  static getStrictSearch (search: string | number, field: string) {
Where is this used?

2023-11-28 20:53 UTC, ArtemiiLiakh approved these changes

2023-11-29 14:11 UTC, illiakroshka requested changes

2023-11-29 14:11 UTC, illiakroshka commented on src/v2/api/responses/StudentResponse.ts
> +    role: string;
In swagger it shows like number 
![image](https://github.com/fictadvisor/fictadvisor-api/assets/116638814/0fe09acf-7037-4b33-8737-17adce7cbbf3)

2023-11-30 19:00 UTC, illiakroshka commented
It looks like roles does't work. Sends back all students istead of students with moderator or admin role

![image](https://github.com/fictadvisor/fictadvisor-api/assets/116638814/11795576-92e5-45c6-b766-fdd2d382a7c2)

2023-12-01 14:48 UTC, illiakroshka approved these changes

2024-01-04 14:44 UTC, fokaaas requested changes

2024-01-04 14:44 UTC, fokaaas commented on src/v2/api/pipes/AllStudentsPipe.ts
> +      await Promise.all(query.groups?.map((groupId) => this.groupByIdPipe.transform(groupId)));
use mapAsync in utils

2024-01-04 14:44 UTC, fokaaas commented on src/v2/security/PERMISSION.ts
> +  ADMIN_STUDENTS_GET = 'admin.students.get'
just students.get

2024-01-04 15:59 UTC, fokaaas approved these changes

2024-01-04 15:59 UTC, merged