bug #863: Changed summary in User endpoints
fictadvisor/fictadvisor-api pull request #881
Opened 2023-11-30 12:10 UTC by fujivara

- Post /v2/users/{userId}/contacts
- Patch /v2/users/{userId}/contacts/{contactId}
- Delete /v2/users/{userId}/contacts/{contactId}
- Delete /v2/users/{userId}/student
- Patch /v2/users/{userId}/student

closes #863

2023-12-01 18:48 UTC, JessFreak requested changes

2023-12-01 18:48 UTC, JessFreak commented on src/v2/api/controllers/UserController.ts
> +    summary: 'Update user\'s contact',
add 'by contact\'s id'

2023-12-01 18:48 UTC, JessFreak commented on src/v2/api/controllers/UserController.ts
> +    summary: 'Delete user\'s contact',
add 'by contact\'s id'

2024-01-04 21:33 UTC, JessFreak approved these changes

2024-01-04 22:18 UTC, Dmutre commented
QA зробтв перевірку, все працює, єдине питання було до правильності роботи 
Patch /v2/users/{userId}/contacts/{contactId}
Проте це вже справа не цього пр

2024-01-05 20:05 UTC, fokaaas approved these changes

2024-01-06 16:28 UTC, closed without merging